name: Greet User on Merged PR

on:
  pull_request:
    types:
      - closed

jobs:
  greet_user:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const message = `Thank you, @${prAuthor}, for your contribution! 🚀 Your PR has been merged.`;

            // Post a comment on the PR
            github.issues.createComment({
              body: message
            });
